#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true
xsetroot -cursor_name left_ptr &

bspc config focus_follows_pointer true
bspc config top_padding 26

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Auto Início ##
setxkbmap -layout br -option compose:rwin &
nitrogen --restore &
xset -dpms &
xset s off &
# picom -f &
